FROM node:20-alpine

# Adiciona as bibliotecas que o Prisma precisa para funcionar no Alpine
RUN apk add --no-cache openssl libc6-compat

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate
EXPOSE 3000
CMD ["node", "index.js"]